'use client';

import { formatDistanceToNow } from 'date-fns';
import { SearchQuery } from '@/types/observatory';

interface LearningActivityProps {
  queries: SearchQuery[];
  loading: boolean;
}

export default function LearningActivity({ queries, loading }: LearningActivityProps) {
  if (loading) {
    return (
      <div className="bg-white rounded-lg shadow-md border border-gray-200 p-6 animate-pulse">
        <div className="h-6 bg-gray-200 rounded w-1/3 mb-4"></div>
        <div className="space-y-3">
          {[...Array(3)].map((_, i) => (
            <div key={i} className="h-12 bg-gray-200 rounded"></div>
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="bg-white rounded-lg shadow-md border border-gray-200 p-6">
      <h3 className="text-lg font-semibold text-gray-900 mb-1">Learning Activity</h3>
      <p className="text-sm text-gray-500 mb-4">Queries generated by the agent</p>

      {queries.length === 0 ? (
        <p className="text-gray-500 text-sm">No agent-generated queries yet.</p>
      ) : (
        <div className="space-y-4">
          {queries.map((query) => (
            <div key={query.id} className="bg-gray-50 rounded-lg p-4">
              <p className="text-sm text-gray-900">
                <span className="text-gray-500">The agent suggested searching for:</span>
              </p>
              <p className="mt-1 text-sm font-medium text-blue-700">
                &ldquo;{query.query_text}&rdquo;
              </p>
              <div className="mt-2 flex flex-wrap items-center gap-3 text-xs text-gray-500">
                <span>
                  {formatDistanceToNow(new Date(query.created_at), { addSuffix: true })}
                </span>
                <span className="text-gray-300">|</span>
                <span>Run {query.times_run} time{query.times_run !== 1 ? 's' : ''}</span>
                <span className="text-gray-300">|</span>
                <span>Found {query.sources_found} source{query.sources_found !== 1 ? 's' : ''}</span>
                {query.priority_score !== null && (
                  <>
                    <span className="text-gray-300">|</span>
                    <span>Priority: {(query.priority_score * 100).toFixed(0)}%</span>
                  </>
                )}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
